UBC-MDS/SharpEdge

.github/workflows/ci-cd.yml, .gitignore, .readthedocs.yml, CHANGELOG.md, CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md, docs/Makefile, docs/changelog.md, docs/conduct.md, docs/conf.py, docs/contributing.md, docs/example.ipynb, docs/index.md, docs/make.bat, docs/requirements.txt, pyproject.toml, src/sharpedge/__init__.py, tests/test_sharpedge.py
Essentially all bullets from Milestone 1 - Point 3, excluding the last bullet, has been completed.
=> Software structure

src/sharpedge/modulate_image.py
function documentation for color conversion `modulate_image`
=> feat: add color conversion function documentation

src/sharpedge/frame_image.py
function documentation for image padding `frame_image`
=> feat: add image padding function documentation

src/sharpedge/pooling_image.py
created the pooling_image for the function that will shrink image based on window size and pooling function specified. The function should take in arguments for image being used (2d or 3d numpy array), size of windows for image, pooling function to be used on windows, and color. The final output will be the image after being pooled. (Instead of a numpy array being output the image will be shown using a matplotlib function within the the function).
=> Pooling function

README.md
-Added a summary Paragraph to README outlining high level use of the `sharpedge` package
-Created a list of each function with a 1-2 sentence summary of function description 
-Added a paragraph outlining where `sharpedge` fits in python ecosystem, along with similar packages and what sets `sharpedge` apart from them.
=> summary paragraph, function list, and where package fits

tests/test_utility.py
Adding the missing part to test_zero_size_dimensions(invalid_input):
=> Update test_utility.py, adding missing part of last test

src/sharpedge/pooling_image.py, tests/test_pooling_image.py
-created pooling_image function to resize image array based on pooling function used (mean, median,etc)
-created tests for function with 100% coverage
-added input_checker into function after we have finalized sanity checker
=> Pooling test

poetry.lock, src/sharpedge/reposition_image.py, tests/test_reposition_image.py
- created reposition function to flip img, rotate img, and shift img on x and y axis
- created tests for function with 100% coverage
- added input_checker into function after we have finalized sanity checker
=> Reposition test

src/sharpedge/frame_image.py
=> feat: function commented code cleaned up and add in _input_checker

poetry.lock, pyproject.toml, src/sharpedge/frame_image.py, src/sharpedge/modulate_image.py, src/sharpedge/pca_compression.py, src/sharpedge/pooling_image.py, src/sharpedge/reposition_image.py, tests/test_pca_compression.py
update lock
update input checker reference
fix pca test issue
=> update lock, update input checker reference, fix pca test issue

src/sharpedge/pooling_image.py, tests/test_pooling_image.py
- adding test cases for if image is not a squared array
- adding test cases for non-divisible dimensions
=> adding more test cases based on suggestions

src/sharpedge/modulate_image.py, tests/test_modulate_image.py
- update conversion to luminosity method so easier validation with human eye and test case outputs accordingly
- remove `return` redundancies so branch coverage is 100%
=> Func test color conv

src/sharpedge/frame_image.py
- update function in terms of maximizing flexibility
Still achieve both 100% branch and line coverage. per below.
=> feat: update function for more flexibility in customization

README.md
Now we should have a doc badge stating passing in the README and the rendered documentation page.
=> docs: add documentation status badge

CONDUCT.md, docs/index.md
Update the names of the notebooks in `index.md` so that they can be successfully rendered.
Also change some headings in `CONDUCT.md` so that all the heading are in consecutive order.
=> Fix references in `index.md`

src/sharpedge/seam_carving.py
- Added leading underscore to intermediate function names.
- Specify in docstrings they are private functions to be invoked by `seam_carve()` only.
=> Added underscore to intermediate function names and updated docstrings

docs/image_framing.ipynb
fix: Feedback addressed by Jenny - peer review feedback to include arguments of function in tutorial (on top of docstring).
=> peer review: `frame_image` documentation update

docs/image_seam_carving.ipynb
fix: Feedback addressed by Jenny - peer review feedback to fix grammar mistake in seam_carve docs`
=> Peer Review: seam_carve fix grammar mistake

src/sharpedge/modulate_image.py
TA and peer review feedback to break down functions into intermediate functions for easier review
Function split into three intermediate functions:
- mode_conversion
- channel_swap
- channel_extract
All test cases still pass, and both branch and line code coverage at 100%. Per below
=> fix: Feedback addressed by Jenny - `modulate_image`

README.md
Once you have your functions implemented, I'd also add some example images under each function on the README file to better illustrate what they do.
After discussing with Rubia, we decided to guide users to the documentation tutorials instead of adding example images directly to the README.
=> fix: Feedback addressed by Archer - Added a note in the README to guide users to the documentation for examples

tests/test_frame_image.py, tests/test_modulate_image.py
fix: Feedback addressed by Jenny - TA feedback on tackle a lot of error cases by breaking down test functions
Note only test file structure change, all tests still pass per below.
=> TA Feedback: tackle a lot of test cases

docs/conf.py
change theme to `sphix_rtd_theme`
visualization below:
=> build: change html theme to rtd (from press) as press has minial updates
